export type ThemeColors = {
  foreground: string;
  pickerForeground: string;
  pickerSelectedForeground: string;
  brandCode: string;
  brandTerminal: string;
  operationType: string;
  modelName: string;
  primary: string;
  planMode: string;
  selection: string;
  thinking: string;
  success: string;
  error: string;
  info: string;
  background: string;
  surface: string;
  dialogSurface: string;
  thinkingBorder: string;
  dimSeparator: string;
};

export type Theme = {
  name: string;
  colors: ThemeColors;
};

export const THEMES: Theme[] = [
  {
    name: "CodeTerminal",
    colors: {
      foreground: "#E4E4E7",
      pickerForeground: "#FDE68A",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#C4B5FD",
      brandTerminal: "#22D3EE",
      operationType: "#A78BFA",
      modelName: "#22D3EE",
      primary: "#C4B5FD",
      planMode: "#A78BFA",
      selection: "#C4B5FD",
      thinking: "#22D3EE",
      success: "#10B981",
      error: "#FB7185",
      info: "#22D3EE",
      background: "#0D0D12",
      surface: "#14141C",
      dialogSurface: "#1A1A24",
      thinkingBorder: "#22D3EE",
      dimSeparator: "#9CA3AF",
    },
  },

  {
    name: "Dracula",
    colors: {
      foreground: "#F8F8F2",
      pickerForeground: "#FFB86C",
      pickerSelectedForeground: "#FFB86C",
      brandCode: "#BD93F9",
      brandTerminal: "#8BE9FD",
      operationType: "#50FA7B",
      modelName: "#FF79C6",
      primary: "#BD93F9",
      planMode: "#FF79C6",
      selection: "#44475A",
      thinking: "#8BE9FD",
      success: "#50FA7B",
      error: "#FF5555",
      info: "#8BE9FD",
      background: "#282A36",
      surface: "#343746",
      dialogSurface: "#3B3F51",
      thinkingBorder: "#8BE9FD",
      dimSeparator: "#6272A4",
    },
  },

  {
    name: "Tokyo Night",
    colors: {
      foreground: "#C0CAF5",
      pickerForeground: "#7DCFFF",
      pickerSelectedForeground: "#A6E3A1",
      brandCode: "#7AA2F7",
      brandTerminal: "#7DCFFF",
      operationType: "#9ECE6A",
      modelName: "#BB9AF7",
      primary: "#7AA2F7",
      planMode: "#BB9AF7",
      selection: "#33467C",
      thinking: "#7DCFFF",
      success: "#9ECE6A",
      error: "#F7768E",
      info: "#7DCFFF",
      background: "#1A1B26",
      surface: "#24283B",
      dialogSurface: "#2A2E42",
      thinkingBorder: "#7DCFFF",
      dimSeparator: "#565F89",
    },
  },

  {
    name: "Catppuccin Mocha",
    colors: {
      foreground: "#CDD6F4",
      pickerForeground: "#FAB387",
      pickerSelectedForeground: "#F9E2AF",
      brandCode: "#CBA6F7",
      brandTerminal: "#89DCEB",
      operationType: "#A6E3A1",
      modelName: "#F5C2E7",
      primary: "#CBA6F7",
      planMode: "#F5C2E7",
      selection: "#585B70",
      thinking: "#89DCEB",
      success: "#A6E3A1",
      error: "#F38BA8",
      info: "#89DCEB",
      background: "#1E1E2E",
      surface: "#313244",
      dialogSurface: "#45475A",
      thinkingBorder: "#89DCEB",
      dimSeparator: "#7F849C",
    },
  },

  {
    name: "Nord",
    colors: {
      foreground: "#F8FAFF",
      pickerForeground: "#8BE9FD",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#8BE9FD",
      brandTerminal: "#FF79C6",
      operationType: "#A6E22E",
      modelName: "#FFD866",
      primary: "#8BE9FD",
      planMode: "#FF79C6",
      selection: "#305F8A",
      thinking: "#8BE9FD",
      success: "#A6E22E",
      error: "#FF6188",
      info: "#8BE9FD",
      background: "#1B2330",
      surface: "#253147",
      dialogSurface: "#2E3C56",
      thinkingBorder: "#8BE9FD",
      dimSeparator: "#7DA2C1",
    },
  },

  {
    name: "Gruvbox Dark",
    colors: {
      foreground: "#FFF2CC",
      pickerForeground: "#FFD866",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#FFD866",
      brandTerminal: "#8BE9FD",
      operationType: "#A9DC76",
      modelName: "#FF79C6",
      primary: "#FFD866",
      planMode: "#FF79C6",
      selection: "#5A4A2F",
      thinking: "#8BE9FD",
      success: "#A9DC76",
      error: "#FB7185",
      info: "#8BE9FD",
      background: "#201B12",
      surface: "#312619",
      dialogSurface: "#463A2E",
      thinkingBorder: "#8BE9FD",
      dimSeparator: "#B08968",
    },
  },

  {
    name: "Solarized Dark",
    colors: {
      foreground: "#FDF6E3",
      pickerForeground: "#2AA198",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#3AB4F2",
      brandTerminal: "#2AA198",
      operationType: "#B8F200",
      modelName: "#FF6EC7",
      primary: "#3AB4F2",
      planMode: "#FF6EC7",
      selection: "#003B53",
      thinking: "#2AA198",
      success: "#B8F200",
      error: "#FF6B6B",
      info: "#2AA198",
      background: "#002B36",
      surface: "#073642",
      dialogSurface: "#0E4B5A",
      thinkingBorder: "#2AA198",
      dimSeparator: "#6BB9C8",
    },
  },

  {
    name: "One Dark",
    colors: {
      foreground: "#F5F8FF",
      pickerForeground: "#61AFEF",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#61AFEF",
      brandTerminal: "#56B6C2",
      operationType: "#98C379",
      modelName: "#C678DD",
      primary: "#61AFEF",
      planMode: "#C678DD",
      selection: "#4B5A78",
      thinking: "#56B6C2",
      success: "#98C379",
      error: "#FF6C7A",
      info: "#56B6C2",
      background: "#202430",
      surface: "#2B3140",
      dialogSurface: "#343C4E",
      thinkingBorder: "#56B6C2",
      dimSeparator: "#72809A",
    },
  },

  {
    name: "GitHub Dark",
    colors: {
      foreground: "#F0F6FC",
      pickerForeground: "#58A6FF",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#58A6FF",
      brandTerminal: "#79C0FF",
      operationType: "#3FB950",
      modelName: "#BC8CFF",
      primary: "#58A6FF",
      planMode: "#BC8CFF",
      selection: "#21415E",
      thinking: "#79C0FF",
      success: "#3FB950",
      error: "#FF7B72",
      info: "#79C0FF",
      background: "#0A1018",
      surface: "#111827",
      dialogSurface: "#1B2430",
      thinkingBorder: "#79C0FF",
      dimSeparator: "#8B949E",
    },
  },

  {
    name: "GitHub Light",
    colors: {
      foreground: "#24292F",
      pickerForeground: "#0969DA",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#0969DA",
      brandTerminal: "#8250DF",
      operationType: "#1A7F37",
      modelName: "#CF222E",
      primary: "#0969DA",
      planMode: "#8250DF",
      selection: "#D0D7DE",
      thinking: "#1A7F37",
      success: "#1A7F37",
      error: "#CF222E",
      info: "#0969DA",
      background: "#F6F8FA",
      surface: "#FFFFFF",
      dialogSurface: "#F3F4F6",
      thinkingBorder: "#0969DA",
      dimSeparator: "#6E7781",
    },
  },

  {
    name: "Synthwave",
    colors: {
      foreground: "#F5F5F5",
      pickerForeground: "#FFB3F1",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#FF7EDB",
      brandTerminal: "#00F5FF",
      operationType: "#72F1B8",
      modelName: "#FF5C8D",
      primary: "#FF7EDB",
      planMode: "#FF5C8D",
      selection: "#3A2E5E",
      thinking: "#00F5FF",
      success: "#72F1B8",
      error: "#FF5C8D",
      info: "#00F5FF",
      background: "#241B2F",
      surface: "#2D2240",
      dialogSurface: "#382B50",
      thinkingBorder: "#00F5FF",
      dimSeparator: "#7A6F9B",
    },
  },

  {
    name: "Matrix",
    colors: {
      foreground: "#00FF41",
      pickerForeground: "#AAFFB1",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#00FF41",
      brandTerminal: "#00FF41",
      operationType: "#00FF41",
      modelName: "#00CC33",
      primary: "#00FF41",
      planMode: "#00CC33",
      selection: "#003B00",
      thinking: "#00FF41",
      success: "#00FF41",
      error: "#FF3131",
      info: "#00FF41",
      background: "#000000",
      surface: "#061006",
      dialogSurface: "#0A160A",
      thinkingBorder: "#00FF41",
      dimSeparator: "#3A5F3A",
    },
  },

  {
    name: "Rose Pine",
    colors: {
      foreground: "#E0DEF4",
      pickerForeground: "#F6C177",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#C4A7E7",
      brandTerminal: "#9CCFD8",
      operationType: "#31748F",
      modelName: "#EBBCBA",
      primary: "#C4A7E7",
      planMode: "#EBBCBA",
      selection: "#403D52",
      thinking: "#9CCFD8",
      success: "#31748F",
      error: "#EB6F92",
      info: "#9CCFD8",
      background: "#191724",
      surface: "#1F1D2E",
      dialogSurface: "#26233A",
      thinkingBorder: "#9CCFD8",
      dimSeparator: "#6E6A86",
    },
  },

  {
    name: "Everforest",
    colors: {
      foreground: "#D3C6AA",
      pickerForeground: "#A7C080",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#7FBBB3",
      brandTerminal: "#83C092",
      operationType: "#A7C080",
      modelName: "#D699B6",
      primary: "#7FBBB3",
      planMode: "#D699B6",
      selection: "#3A4A42",
      thinking: "#83C092",
      success: "#A7C080",
      error: "#E67E80",
      info: "#83C092",
      background: "#272E33",
      surface: "#2E383C",
      dialogSurface: "#374145",
      thinkingBorder: "#83C092",
      dimSeparator: "#859289",
    },
  },

  {
    name: "Ayu Dark",
    colors: {
      foreground: "#E6B450",
      pickerForeground: "#FFB454",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#59C2FF",
      brandTerminal: "#95E6CB",
      operationType: "#AAD94C",
      modelName: "#D2A6FF",
      primary: "#59C2FF",
      planMode: "#D2A6FF",
      selection: "#273747",
      thinking: "#95E6CB",
      success: "#AAD94C",
      error: "#F07178",
      info: "#95E6CB",
      background: "#0B0E14",
      surface: "#11151C",
      dialogSurface: "#1A1F29",
      thinkingBorder: "#95E6CB",
      dimSeparator: "#6C7A89",
    },
  },

  {
    name: "Monokai",
    colors: {
      foreground: "#F8F8F2",
      pickerForeground: "#F8F8F2",
      pickerSelectedForeground: "#FFD866",
      brandCode: "#FFD866",
      brandTerminal: "#78DCE8",
      operationType: "#A9DC76",
      modelName: "#AB9DF2",
      primary: "#FFD866",
      planMode: "#AB9DF2",
      selection: "#49483E",
      thinking: "#78DCE8",
      success: "#A9DC76",
      error: "#FF6188",
      info: "#78DCE8",
      background: "#272822",
      surface: "#34352E",
      dialogSurface: "#3E3D32",
      thinkingBorder: "#78DCE8",
      dimSeparator: "#75715E",
    },
  },

  {
    name: "Night Owl",
    colors: {
      foreground: "#D6DEEB",
      pickerForeground: "#82AAFF",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#82AAFF",
      brandTerminal: "#7FDBCA",
      operationType: "#22DA6E",
      modelName: "#C792EA",
      primary: "#82AAFF",
      planMode: "#C792EA",
      selection: "#2C3043",
      thinking: "#7FDBCA",
      success: "#22DA6E",
      error: "#EF5350",
      info: "#7FDBCA",
      background: "#011627",
      surface: "#0B1E2D",
      dialogSurface: "#122738",
      thinkingBorder: "#7FDBCA",
      dimSeparator: "#637777",
    },
  },

  {
    name: "Cyberpunk",
    colors: {
      foreground: "#F5F5F5",
      pickerForeground: "#FF6EC7",
      pickerSelectedForeground: "#FFFFFF",
      brandCode: "#FF00FF",
      brandTerminal: "#00FFFF",
      operationType: "#39FF14",
      modelName: "#FF6EC7",
      primary: "#FF00FF",
      planMode: "#FF6EC7",
      selection: "#3B1F5C",
      thinking: "#00FFFF",
      success: "#39FF14",
      error: "#FF3131",
      info: "#00FFFF",
      background: "#0A0A0F",
      surface: "#151520",
      dialogSurface: "#1F1F2E",
      thinkingBorder: "#00FFFF",
      dimSeparator: "#7A7A99",
    },
  },
];
export const DEFAULT_THEME = THEMES.find((t) => t.name === "CodeTerminal")!;
